### ISSUE TITLE
PWA plugin is caching form submission urls, stopping them from submitting

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#151]
## Describe the bug

eleventy-plugin-pwa goes through and adds all routes it finds to the `precacheManifest`, which is normally what we want. The problem is, our form thank-you pages are being caught in there, which is _not_ what we want, since Netlify uses those to actually receive the POST submissions. 

I have removed PWA support from the site for now (#150) - let's find a way to add it back in. I think somehow ignoring those pages will the the best way, but it would be nice to be able to do that at the template level (ie adding some sort of "do not cache" flag to the head matter) than maintaining a list at the 11ty configuration level.

**Comment by clandau** [comment]
I was looking into this a bit...do you think this is doable using that plugin? There's not much documentation there, but the PWA thing is new to me. I may need to book time with you to discuss.

**Comment by danieltott** [comment]
I _think_ we just need to make sure the form thank you pages are getting excluded from being cached. I'm not sure the exact approach, but it seems possible. I'm pretty sure if we just don't ever cache those pages, then things will work the way we expect. I guess maybe I'd want to look into if there are any other gotchas re: this plugin and netlify/11ty pages. For instance, do netlify analytics still get counted if the page is cached as a PWA? Not sure.

**Comment by mtfoley** [comment]
Totally new here but I was looking at this issue and I may take a shot at contributing. Meanwhile looking over the source in eleventy-plugin-pwa it appears to pass its config options into the workbox generateSW function https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.generateSW 

my thought would be to look at the ignoreGlobs config option since it doesn’t look like eleventy-plugin-pwa overrides it.

**Comment by danieltott** [comment]
@mtfoley if you want to give it a shot, let me know!
