### ISSUE TITLE
Automate updating member data

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#208]
## Issue Context

Currently, when we add a new member to the `members.json` file, we then have to run a command to get updated member data from github. The problem is, the user needs to be authenticated with github on the command line to run this command.

This limitation prevents us from simply running the fetch on every build and excluding the `membersData.json` file from version control.

Is there a way to automate (via github actions perhaps) running this command and then committing the result?

Are there better solutions for this?

**Comment by BogDAAAMN** [comment]
I would love to work on it tomorrow morning if possible <3

**Comment by danieltott** [comment]
@BogDAAAMN for sure! First step will be outlining your approach here - what will happen when, relationship to pull requests, all that kind of stuff. Very excited to see what you're thinking!

**Comment by rhdeck** [comment]
This could use a push-triggered workflow using the paths filter described here: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths. The paths will likely be `src/_data/members/members.json`

And then you would probably perform 4 steps: 
1. a quick `yarn` to marshal the dependencies 
2. execute the script `virtualcoffee.io/scripts/update-member-data.js`
3. commit `memberData.json`
4. push the commit. 

I do something a lot like this (though on a dispatch rather than push) in another repository, which we could raid: https://github.com/rhdeck/fastlane-js/blob/master/.github/workflows/rubygem-response.yml

**Comment by BogDAAAMN** [comment]
Yesss @rhdeck, followed your suggested steps and wrote them down in PR #211. Struggling to `git push` back to the right refs that are pointing to the PR. But I would love to pair with @rhdeck and @danieltott to see how usually checking out and pushing back to a PR works.

**Comment by danieltott** [comment]
Hey @BogDAAAMN I ended up fixing this when I had to fix an issue with the sponsors posting. Member data is updating on builds now!

**Comment by BogDAAAMN** [comment]
Nice @danieltott!! I am trying to take a look at it, but I don't seem to find it 😢  Is it an eleventy or netlify functions thing?

**Comment by danieltott** [comment]
@BogDAAAMN so now it's pulling the data down in the 11ty build instead of trying to store a json file: https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/src/_data/members/memberData.js

**Comment by BogDAAAMN** [comment]
Got it! Thank you @danieltott
