### ISSUE TITLE
Update site to reflect new membership guidelines

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/virtualcoffee.io#616]
- active volunteers must invite new members
- new members must join a coffee first 
- slack invites to members who attend should be sent within 24 hrs. 
- we believe that live interaction is part of what makes VC special; we continually try to provide support to all of our members no matter what stage they're at; we value the health of the community over growth every single day.

**Comment by JesseRWeigel** [comment]
Is this still needed? Can I do it?

**Comment by danieltott** [comment]
@JesseRWeigel we're about to have some more changes to this process so let's hold off for the moment 👍🏼

**Comment by adiati98** [comment]
Hey @BekahHW & @danieltott 
Is this issue related to updating the header (as the pic attached below) of the [Join Virtual Coffee](https://virtualcoffee.io/resources/virtual-coffee/join-virtual-coffee) page?

Because while I was updating the "Guide to VC" page, I was thinking of updating this page since we started to open for new members.
If that is the case, I'll hold it as well.

Thanks!

![join-vc-header](https://user-images.githubusercontent.com/45172775/187361241-412f1cb2-122c-4ebc-95c6-e40a312066b6.JPG)

**Comment by BekahHW** [comment]
We're working on a waitlist rn so once we get that going, this will definitely need to be updated.
