### ISSUE TITLE
Add section or page about handling merge conflicts

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#628]
### Type of Change

New section on existing page

### URL of existing page

https://virtualcoffee.io/resources/open-source

### Context for content change

What do you do when there's a merge conflict?

This can be a confusing experience - it'd be great to have either a section or a whole new page for this.

This could either be in [Git & GitHub 101](https://virtualcoffee.io/resources/open-source/git-101), [Contributor Guide](https://virtualcoffee.io/resources/open-source/contributor-guide), or an entire new page.

**Comment by adiati98** [comment]
@danieltott we can put it in the [Git & GitHub 101 after the "Synchronizing changes locally" section](https://virtualcoffee.io/resources/open-source/git-101#synchronizing-changes-locally) as a continuation.
![synchronizing changes locally](https://user-images.githubusercontent.com/45172775/188114770-888cf806-edc2-420c-a79f-95448c5945a0.JPG)

We can insert this part (pic attached) of my article [How To Use GitHub For Project Collaboration — Based on Agile Method](https://adiati.com/how-to-use-github-for-project-collaboration-based-on-agile-method) if you will.

![fix conflict](https://user-images.githubusercontent.com/45172775/188114805-1a421a20-6aea-4a46-b887-6152218775e9.JPG)

Also, because I reread it, slight adjustments/edits might be needed within the "Synchronizing changes locally" section, which I will make an issue and PR for.

If you approve the above suggestions for fixing conflicts, I can work on them along with the edits in this issue 😄!

**Comment by danieltott** [comment]
@adiati98 sounds good! Thank you!!!
